#!/data/data/com.termux/files/usr/bin/sh
#export DISPLAY=:0  # 在10号屏幕上打开程序
#Xvnc --SecurityTypes=None $DISPLAY &  # 启动vnc
#sleep 1s  # 等待vnc启动
openbox-session & # 打开窗口管理器
#xsetroot -solid gray # 把背景弄成灰色
#pypanel & # 打开pypanel
aterm &  # 开启终端
startxfce4 & # 开启xfce桌面
#lxqt-session &
